window.UAVMap = (() => {
  let map, markers=[], routeLine;
  const icon=(type,label)=>L.divIcon({className:'',html:`<div class="uav-marker ${type}">${label}</div>`,iconSize:[30,30],iconAnchor:[15,15]});
  function addRotationControl(){if(typeof map.setBearing!=='function')return;const RotateControl=L.Control.extend({options:{position:'bottomright'},onAdd(){const container=L.DomUtil.create('div','leaflet-bar map-rotate-control');[['↶','Повернути на 15° ліворуч',-15],['N','Північ угорі',0],['↷','Повернути на 15° праворуч',15]].forEach(([label,title,turn])=>{const button=L.DomUtil.create('a','',container);button.href='#';button.title=title;button.textContent=label;L.DomEvent.on(button,'click',event=>{L.DomEvent.stop(event);map.setBearing(turn===0?0:(map.getBearing()+turn)%360);});});return container;}});map.addControl(new RotateControl());}
  function init(onClick,onDrag,onSelect) { map=L.map('map',{zoomControl:false,rotate:true,bearing:0,touchRotate:true,shiftKeyRotate:true}).setView([50.4501,30.5234],12);L.control.zoom({position:'bottomright'}).addTo(map);const baseLayers={Картографічна:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),Супутникова:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}),Рельєфна:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'}),Темна:L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'})};baseLayers.Картографічна.addTo(map);L.control.layers(baseLayers,null,{position:'bottomright',collapsed:true}).addTo(map);addRotationControl();map.on('click',e=>onClick(e.latlng)); window._uavDrag=onDrag;window._uavSelect=onSelect; }
  function render(points) { markers.forEach(marker=>map.removeLayer(marker));markers=[];if(routeLine){map.removeLayer(routeLine);routeLine=null;} points.forEach((point,index)=>{const type=index===0?'start':index===points.length-1?'end':'middle', label=index===0?'A':index===points.length-1?'B':String(index+1), marker=L.marker(point,{icon:icon(type,label),draggable:true}).addTo(map);marker.on('dragend',e=>window._uavDrag(index,e.target.getLatLng()));marker.on('click',()=>window._uavSelect(index));markers.push(marker);});if(points.length>1) routeLine=L.polyline(points,{color:'#25c9a7',weight:4,opacity:.92,dashArray:'10 7'}).addTo(map); }
  function fitRoute(points){if(points.length>1)map.fitBounds(L.latLngBounds(points).pad(.25));else if(points[0])map.setView(points[0],14);}
  return {init,render,fitRoute};
})();
